# Generated by Django 6.0.2 on 2026-02-23 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('country_selected', models.CharField(blank=True, max_length=100)),
                ('suggestion_selected', models.CharField(blank=True, max_length=200)),
                ('passed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('has_map_icon', models.BooleanField(default=False)),
                ('is_selected', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('journey_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='automation.journeyrun')),
            ],
        ),
        migrations.CreateModel(
            name='ListingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('is_selected', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('journey_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='automation.journeyrun')),
            ],
        ),
        migrations.CreateModel(
            name='ListingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('image_urls', models.JSONField(default=list)),
                ('page_url', models.URLField(blank=True, max_length=1000)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('journey_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_details', to='automation.journeyrun')),
            ],
        ),
        migrations.CreateModel(
            name='StepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('test_case', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('passed', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=500)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('journey_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='automation.journeyrun')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='NetworkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('console', 'Console'), ('network', 'Network')], max_length=20)),
                ('message', models.TextField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('journey_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_logs', to='automation.journeyrun')),
                ('step_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automation.stepresult')),
            ],
        ),
    ]
